[package]
name = "back_end"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
surrealdb = "2.0.1"
tokio = { version = "1.40.0", features = ["full"] }
tower-http = "0.6.0"
